/**
 * Catalogue statique de toutes les ressources du répertoire base/
 * Organisé par catégorie avec métadonnées pour la page /guides-techniques
 */
import pagesMap from './pagesMap.json'

export const CATEGORIES = [
  { slug: 'toutes',                  label: 'Toutes les ressources',               icon: '📚', color: '#64748B' },
  { slug: 'charpente-couverture',    label: 'Charpente, Couverture & Étanchéité',  icon: '🏠', color: '#8B5CF6' },
  { slug: 'facade',                  label: 'Façade',                               icon: '🧱', color: '#F97316' },
  { slug: 'amenagement-exterieur',   label: 'Aménagement Extérieur',               icon: '🌿', color: '#10B981' },
  { slug: 'chauffage',               label: 'Chauffage',                            icon: '🔥', color: '#EF4444' },
  { slug: 'cloisons-menuiseries',    label: 'Cloisons & Menuiseries',              icon: '🚪', color: '#06B6D4' },
  { slug: 'divers',                  label: 'Guides & Rénovation',                 icon: '📖', color: '#3B82F6' },
  { slug: 'electricite',             label: 'Électricité',                          icon: '⚡', color: '#EAB308' },
  { slug: 'fondations',              label: 'Fondations & Infrastructures',         icon: '⚙️', color: '#6B7280' },
  { slug: 'revetements-interieurs',  label: 'Revêtements Intérieurs',              icon: '🪵', color: '#D97706' },
  { slug: 'structure-gros-oeuvre',   label: 'Structure & Gros Œuvre',             icon: '🏗️', color: '#0EA5E9' },
  { slug: 'ventilation',             label: 'Ventilation',                          icon: '💨', color: '#14B8A6' },
  { slug: 'videos',                  label: 'Tutoriels Vidéo REX BP',              icon: '🎬', color: '#EC4899' },
]

/** Type de badge pour chaque document */
const TYPE = {
  MEMO:      { label: 'Mémo Chantier',    color: '#8B5CF6' },
  FICHE:     { label: 'Fiche Technique',  color: '#0EA5E9' },
  RAPPORT:   { label: 'Rapport REX BP',   color: '#EF4444' },
  CALEPIN:   { label: 'Calepin',          color: '#10B981' },
  GUIDE:     { label: 'Guide',            color: '#F97316' },
  PLAQUETTE: { label: 'Plaquette',        color: '#06B6D4' },
  SCHEMAS:   { label: 'Schémathèque',     color: '#3B82F6' },
  PV:        { label: 'PV Réception',     color: '#D97706' },
  AUTOCONTR: { label: 'Autocontrôle',     color: '#EAB308' },
  VIDEO:     { label: 'Vidéo',            color: '#EC4899' },
}

// Chemin de base pour l'API (relatif depuis base/)
// On encode les deux segments pour gérer accents, espaces, virgules…
const B = (cat, file) => `/api/docs/${encodeURIComponent(cat)}/${encodeURIComponent(file)}`

export const RESOURCES = [

  /* ══════════════════════════════════════════════════════
     CHARPENTE, COUVERTURE & ÉTANCHÉITÉ
  ══════════════════════════════════════════════════════ */
  {
    id: 'cha-01', category: 'charpente-couverture',
    title: 'Couvertures Ardoises & Tuiles',
    desc: 'Mémo chantier AQC sur la mise en œuvre des couvertures ardoises et tuiles, points de vigilance et pathologies courantes.',
    type: TYPE.MEMO, url: B('Charpente, couverture, étanchéité', 'Memo-Chantier-Couvertures-Ardoises-Tuiles-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'cha-02', category: 'charpente-couverture',
    title: 'Isolation des Combles Perdus par Soufflage',
    desc: 'Mémo chantier AQC dédié à l\'isolation des combles perdus par soufflage — préparation, mise en œuvre, réception.',
    type: TYPE.MEMO, url: B('Charpente, couverture, étanchéité', 'Memo-Chantier-Isolation-Combles-Perdus-Soufflage-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'cha-03', category: 'charpente-couverture',
    title: 'Relevés d\'Étanchéité — Terrasses Béton Non Isolées',
    desc: 'Mémo chantier AQC sur les relevés d\'étanchéité des toitures-terrasses béton non isolées.',
    type: TYPE.MEMO, url: B('Charpente, couverture, étanchéité', 'Memo-Chantier-Releves-Etancheite-Non-Isoles-Terrasses-Beton-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     FAÇADE
  ══════════════════════════════════════════════════════ */
  {
    id: 'fac-01', category: 'facade',
    title: 'Enduit Monocouche sur Façades Maçonnées',
    desc: 'Mémo chantier AQC sur la mise en œuvre des enduits monocouches sur façades maçonnées, points clés et erreurs à éviter.',
    type: TYPE.MEMO, url: B('Façade', 'Memo-Chantier-Enduit-Monocouche-Facades-Maconnees-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'fac-02', category: 'facade',
    title: 'Façades — Protections Contre le Ruissellement',
    desc: 'Mémo chantier AQC sur les dispositifs de protection des façades contre les ruissellements d\'eau.',
    type: TYPE.MEMO, url: B('Façade', 'Memo-Chantier-Facades-Protections-Ruissellements-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'fac-03', category: 'facade',
    title: 'Réparation Ponctuelle de Bétons en Façade',
    desc: 'Mémo chantier AQC sur les techniques de réparation ponctuelle des bétons dégradés en façade.',
    type: TYPE.MEMO, url: B('Façade', 'Memo-Chantier-Reparation-Ponctuelle-Betons-Facade-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     AMÉNAGEMENT EXTÉRIEUR
  ══════════════════════════════════════════════════════ */
  {
    id: 'ext-01', category: 'amenagement-exterieur',
    title: 'Infiltrations — Liaisons Menuiseries / Gros Œuvre (Outre-Mer)',
    desc: 'Fiche pathologie bâtiment D01 — infiltrations aux liaisons menuiseries extérieures / gros œuvre en Outre-Mer.',
    type: TYPE.FICHE, url: B('aménagement extérieur', 'Fiche-Pathologie-Batiment-D01-Infiltrations-Liaisons-Menuiseries-Exterieures-Gros-oeuvre-Outre-Mer-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ext-02', category: 'amenagement-exterieur',
    title: 'Infiltrations — Seuil de Porte-Fenêtre (Outre-Mer)',
    desc: 'Fiche pathologie bâtiment D02 — infiltrations d\'eau au seuil de porte-fenêtre en Outre-Mer.',
    type: TYPE.FICHE, url: B('aménagement extérieur', 'Fiche-Pathologie-Batiment-D02-Infiltrations-Eau-Seuil-Porte-Fenetre-Outre-Mer-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ext-03', category: 'amenagement-exterieur',
    title: 'Désordres sur Enduits Monocouches',
    desc: 'Fiche pathologie bâtiment D03 — désordres sur enduits monocouches, causes et remèdes.',
    type: TYPE.FICHE, url: B('aménagement extérieur', 'Fiche-Pathologie-Batiment-D03-Desordres-Enduits-Monocouches-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ext-04', category: 'amenagement-exterieur',
    title: 'Avant de Rénover — État Extérieur & Environnement',
    desc: 'Plaquette AQC : diagnostic de l\'état extérieur et de l\'environnement avant rénovation.',
    type: TYPE.PLAQUETTE, url: B('aménagement extérieur', 'Plaquette-02-Avant-Renover-Etat-Exterieur-Environnement-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ext-05', category: 'amenagement-exterieur',
    title: 'Avant de Rénover — Piscine Privée à Usage Familial',
    desc: 'Plaquette AQC : points de contrôle avant la rénovation d\'une piscine privée à usage familial.',
    type: TYPE.PLAQUETTE, url: B('aménagement extérieur', 'Plaquette-04-Avant-Renover-Piscine-Privee-Usage-Familial-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ext-06', category: 'amenagement-exterieur',
    title: 'Rénover son Habitation — Réaliser une Véranda',
    desc: 'Plaquette AQC : guide pratique pour réaliser une véranda en rénovation, réglementation et mise en œuvre.',
    type: TYPE.PLAQUETTE, url: B('aménagement extérieur', 'Plaquette-07-Renover-Habitation-Realiser-Veranda-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     CHAUFFAGE
  ══════════════════════════════════════════════════════ */
  {
    id: 'chf-01', category: 'chauffage',
    title: 'Chauffe-Eau Thermodynamique en Rénovation',
    desc: 'Rapport REX BP AQC sur l\'installation et les performances des chauffe-eau thermodynamiques en rénovation.',
    type: TYPE.RAPPORT, url: B('chauffage', 'Rapport-REX-BP-Chauffe-Eau-Thermodynamique-Renovation-AQC.pdf'),
    source: 'AQC / REX BP',
  },
  {
    id: 'chf-02', category: 'chauffage',
    title: 'Chaufferie Bois en Rénovation',
    desc: 'Rapport REX BP AQC sur la conception et la mise en œuvre des chaufferies bois en rénovation.',
    type: TYPE.RAPPORT, url: B('chauffage', 'Rapport-REX-BP-Chaufferie-Bois-Renovation-AQC.pdf'),
    source: 'AQC / REX BP',
  },
  {
    id: 'chf-03', category: 'chauffage',
    title: 'Pompe à Chaleur en Rénovation',
    desc: 'Rapport REX BP AQC sur l\'installation et le dimensionnement des pompes à chaleur en rénovation.',
    type: TYPE.RAPPORT, url: B('chauffage', 'Rapport-REX-BP-Pompe-A-Chaleur-En-Renovation-AQC.pdf'),
    source: 'AQC / REX BP',
  },

  /* ══════════════════════════════════════════════════════
     CLOISONS, DOUBLAGES & MENUISERIES INTÉRIEURES
  ══════════════════════════════════════════════════════ */
  {
    id: 'clo-01', category: 'cloisons-menuiseries',
    title: 'Isolement Acoustique des Locaux — Bruits Aériens Intérieurs',
    desc: 'Fiche qualité réglementaire G01 AQC sur l\'isolement des locaux aux bruits aériens intérieurs.',
    type: TYPE.FICHE, url: B('cloisons, doublages et menuiseries intérieures', 'Fiche-Qualite-Reglementaire-G01-Isolement-Locaux-Bruits-Aeriens-Interieurs-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'clo-02', category: 'cloisons-menuiseries',
    title: 'Acoustique dans les Habitations Neuves',
    desc: 'Plaquette AQC sur l\'acoustique dans les habitations neuves, exigences et bonnes pratiques.',
    type: TYPE.PLAQUETTE, url: B('cloisons, doublages et menuiseries intérieures', 'Plaquette-Acoustique-Habitations-Neuves-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'clo-03', category: 'cloisons-menuiseries',
    title: 'Acoustique dans les Logements en Rénovation',
    desc: 'Plaquette AQC sur l\'acoustique dans les logements en rénovation, solutions et réglementation.',
    type: TYPE.PLAQUETTE, url: B('cloisons, doublages et menuiseries intérieures', 'Plaquette-Acoustique-Logements-Renovation-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     ÉLECTRICITÉ
  ══════════════════════════════════════════════════════ */
  {
    id: 'ele-01', category: 'electricite',
    title: 'Installation Électrique des Logements — Attestation EL1',
    desc: 'Fiche attestation AQC EL1 sur la conformité des installations électriques dans les logements.',
    type: TYPE.FICHE, url: B('electricité', 'Fiche-Attestations-Electricite-EL1-Installation-Electrique-Logements-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ele-02', category: 'electricite',
    title: 'Infrastructure de Recharge Véhicules Électriques — Attestation EL2',
    desc: 'Fiche attestation AQC EL2 sur l\'infrastructure de recharge pour véhicules électriques et hybrides.',
    type: TYPE.FICHE, url: B('electricité', 'Fiche-Attestations-Electricite-EL2-Infrastructure-Recharge-Vehicules-Electriques-Hybrides-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ele-03', category: 'electricite',
    title: 'Installation Électrique des Services Généraux — Attestation EL2',
    desc: 'Fiche attestation AQC EL2 sur les installations électriques des services généraux.',
    type: TYPE.FICHE, url: B('electricité', 'Fiche-Attestations-Electricite-EL2-Installation-Electrique-Services-Generaux-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     FONDATIONS & INFRASTRUCTURES
  ══════════════════════════════════════════════════════ */
  {
    id: 'fon-01', category: 'fondations',
    title: 'Fondations de Maisons Individuelles',
    desc: 'Mémo chantier AQC sur la conception et la réalisation des fondations de maisons individuelles.',
    type: TYPE.MEMO, url: B('fondations et infrastructures', 'Memo-Chantier-Fondations-Maisons-Individuelles-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'fon-02', category: 'fondations',
    title: 'Mise en Œuvre des Armatures',
    desc: 'Mémo chantier AQC sur la mise en œuvre correcte des armatures en béton armé.',
    type: TYPE.MEMO, url: B('fondations et infrastructures', 'Memo-Chantier-Mise-En-Oeuvre-Armatures-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'fon-03', category: 'fondations',
    title: 'Principes Parasismiques pour Maisons Individuelles',
    desc: 'Mémo chantier AQC sur les principes parasismiques appliqués aux maisons individuelles.',
    type: TYPE.MEMO, url: B('fondations et infrastructures', 'Memo-Chantier-Principes-Parasismiques-Maison-Individuelle-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     REVÊTEMENTS INTÉRIEURS
  ══════════════════════════════════════════════════════ */
  {
    id: 'rev-01', category: 'revetements-interieurs',
    title: 'Carrelages sur Planchers Chauffants',
    desc: 'Mémo chantier AQC sur la pose de carrelages sur planchers chauffants, précautions et règles de l\'art.',
    type: TYPE.MEMO, url: B('revêtements intérieurs', 'Memo-Chantier-Carrelages-Planchers-Chauffants-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'rev-02', category: 'revetements-interieurs',
    title: 'Sols Carrelés dans les Locaux',
    desc: 'Mémo chantier AQC sur la mise en œuvre des sols carrelés dans les locaux intérieurs.',
    type: TYPE.MEMO, url: B('revêtements intérieurs', 'Memo-Chantier-Sols-Carreles-Locaux-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'rev-03', category: 'revetements-interieurs',
    title: 'Sols Souples Collés',
    desc: 'Mémo chantier AQC sur la pose de sols souples collés, préparation du support et mise en œuvre.',
    type: TYPE.MEMO, url: B('revêtements intérieurs', 'Memo-Chantier-Sols-Souples-Colles-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     STRUCTURE & GROS ŒUVRE
  ══════════════════════════════════════════════════════ */
  {
    id: 'str-01', category: 'structure-gros-oeuvre',
    title: 'Fondations de Maisons Individuelles',
    desc: 'Mémo chantier AQC sur la conception et la réalisation des fondations de maisons individuelles.',
    type: TYPE.MEMO, url: B('tructure et Gros Oeuvre', 'Memo-Chantier-Fondations-Maisons-Individuelles-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'str-02', category: 'structure-gros-oeuvre',
    title: 'Mise en Œuvre des Armatures',
    desc: 'Mémo chantier AQC sur la mise en œuvre correcte des armatures en béton armé.',
    type: TYPE.MEMO, url: B('tructure et Gros Oeuvre', 'Memo-Chantier-Mise-En-Oeuvre-Armatures-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'str-03', category: 'structure-gros-oeuvre',
    title: 'Principes Parasismiques pour Maisons Individuelles',
    desc: 'Mémo chantier AQC sur les principes parasismiques appliqués aux maisons individuelles.',
    type: TYPE.MEMO, url: B('tructure et Gros Oeuvre', 'Memo-Chantier-Principes-Parasismiques-Maison-Individuelle-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     VENTILATION
  ══════════════════════════════════════════════════════ */
  {
    id: 'ven-01', category: 'ventilation',
    title: 'VMC Simple Flux & Double Flux — Fiche Pathologie',
    desc: 'Fiche pathologie bâtiment E08 AQC sur les désordres courants des installations VMC simple et double flux.',
    type: TYPE.FICHE, url: B('ventilation', 'Fiche-Pathologie-Batiment-E08-VMC-Simple-Flux-Double-Flux-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ven-02', category: 'ventilation',
    title: 'VMC Double Flux — Maison Individuelle',
    desc: 'Mémo chantier AQC sur l\'installation de la VMC double flux en maison individuelle.',
    type: TYPE.MEMO, url: B('ventilation', 'Memo-Chantier-VMC-Double-Flux-Maison-Individuelle-AQC.pdf'),
    source: 'AQC',
  },
  {
    id: 'ven-03', category: 'ventilation',
    title: 'VMC Simple Flux — Maison Individuelle',
    desc: 'Mémo chantier AQC sur l\'installation de la VMC simple flux en maison individuelle.',
    type: TYPE.MEMO, url: B('ventilation', 'Memo-Chantier-VMC-Simple-Flux-Maison-Individuelle-AQC.pdf'),
    source: 'AQC',
  },

  /* ══════════════════════════════════════════════════════
     DIVERS — GUIDES & RÉNOVATION (sélection principale)
  ══════════════════════════════════════════════════════ */
  // Calepins de chantier
  {
    id: 'div-01', category: 'divers',
    title: 'Appareils de Chauffage à Granulés — Calepin de Chantier',
    desc: 'Calepin de chantier complet pour l\'installation des appareils de chauffage divisé à granulés.',
    type: TYPE.CALEPIN, url: B('divers', 'Appareils de chauffage divisé à granulés - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-02', category: 'divers',
    title: 'Balcons et Coursives Métalliques Rapportés',
    desc: 'Guide complet sur la conception et la mise en œuvre des balcons et coursives métalliques rapportés.',
    type: TYPE.GUIDE, url: B('divers', 'Balcons et coursives métalliques rapportés.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-03', category: 'divers',
    title: 'Chauffe-Eau Thermodynamique — Calepin de Chantier',
    desc: 'Calepin de chantier dédié à l\'installation des chauffe-eau thermodynamiques.',
    type: TYPE.CALEPIN, url: B('divers', 'Chauffe-eau thermodynamique - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-04', category: 'divers',
    title: 'Chapes et Dalles sur Plancher Bois (Neuf)',
    desc: 'Guide technique sur la réalisation de chapes et dalles sur planchers bois en construction neuve.',
    type: TYPE.GUIDE, url: B('divers', 'Chapes et dalles sur planchers bois - Neuf.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-05', category: 'divers',
    title: 'Chapes et Dalles sur Plancher Bois en Rénovation — Calepin',
    desc: 'Calepin de chantier pour la réalisation de chapes et dalles sur planchers bois existants en rénovation.',
    type: TYPE.CALEPIN, url: B('divers', 'Chapes et dalles sur plancher bois en rénovation - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-06', category: 'divers',
    title: 'Chaudières Hybrides ou PAC Hybrides (Neuf & Rénovation)',
    desc: 'Guide sur les chaudières hybrides et pompes à chaleur hybrides, applicable en neuf et en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Chaudières hybrides ou pompes à chaleur hybrides - Neuf et Rénovation.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-07', category: 'divers',
    title: 'Chauffe-Eaux Solaires — Conception & Dimensionnement (Neuf)',
    desc: 'Guide de conception et dimensionnement des chauffe-eaux solaires en construction neuve.',
    type: TYPE.GUIDE, url: B('divers', 'Chauffe-eau solaires - Conception et dimensionnement - Neuf.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-08', category: 'divers',
    title: 'Chauffe-Eaux Solaires — Conception & Dimensionnement (Rénovation)',
    desc: 'Guide de conception et dimensionnement des chauffe-eaux solaires en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Chauffe-eau solaires - Conception et dimensionnement - Rénovation.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-09', category: 'divers',
    title: 'Chauffe-Eaux Solaires — Installation & Mise en Service (Neuf)',
    desc: 'Guide d\'installation et mise en service des chauffe-eaux solaires en construction neuve.',
    type: TYPE.GUIDE, url: B('divers', 'Chauffe-eau solaires - Installation et mise en service - Neuf.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-10', category: 'divers',
    title: 'Chauffe-Eaux Solaires — Installation & Mise en Service (Rénovation)',
    desc: 'Guide d\'installation et mise en service des chauffe-eaux solaires en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Chauffe-eau solaires - Installation et mise en service - Rénovation.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-11', category: 'divers',
    title: 'Coffres de Volet Roulant — Mise en Œuvre',
    desc: 'Guide technique pour la mise en œuvre des coffres de volet roulant, détails et points de vigilance.',
    type: TYPE.GUIDE, url: B('divers', 'Coffres de volet roulant - Mise en oeuvre.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-12', category: 'divers',
    title: 'Confort d\'Été & Réduction des Surchauffes — 12 Enseignements',
    desc: '12 enseignements clés pour améliorer le confort d\'été et réduire les risques de surchauffe dans les bâtiments.',
    type: TYPE.GUIDE, url: B('divers', 'Confort d\'été et réduction des surchauffes - 12 enseignements à connaître.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-13', category: 'divers',
    title: 'Doubles Fenêtres — Prescription & Mise en Œuvre en Rénovation',
    desc: 'Guide sur la prescription et la mise en œuvre des doubles fenêtres dans les logements en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Doubles fenêtres - Prescription et mise en œuvre en rénovation des logements.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-14', category: 'divers',
    title: 'Encadrements de Baies — Parois Ossature Bois (Calepin)',
    desc: 'Calepin de chantier pour l\'encadrement des baies et l\'intégration des menuiseries dans les parois à ossature bois.',
    type: TYPE.CALEPIN, url: B('divers', 'Encadrements de baies et intégration de menuiseries dans les parois bois - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-15', category: 'divers',
    title: 'Façades en Matériaux Apparents',
    desc: 'Guide sur la conception et la mise en œuvre des façades en matériaux apparents.',
    type: TYPE.GUIDE, url: B('divers', 'Façades en matériaux apparents.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-16', category: 'divers',
    title: 'Fenêtres avec ITE — Calepin de Chantier',
    desc: 'Calepin de chantier pour la pose de fenêtres en contexte d\'isolation thermique par l\'extérieur.',
    type: TYPE.CALEPIN, url: B('divers', 'Fenêtres avec isolation par l\'extérieur - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  // Fiches autocontrôle
  {
    id: 'div-17', category: 'divers',
    title: 'Autocontrôle — Devis et Factures',
    desc: 'Fiche autocontrôle pour vérifier la conformité des devis et factures de travaux.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Devis et Factures.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-18', category: 'divers',
    title: 'Autocontrôle — Fenêtre de Toit',
    desc: 'Fiche autocontrôle pour la réception de la pose d\'une fenêtre de toit.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Fenêtre de toit.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-19', category: 'divers',
    title: 'Autocontrôle — Fenêtres & Menuiseries Extérieures',
    desc: 'Fiche autocontrôle pour la réception des fenêtres et menuiseries extérieures.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Fenêtres et menuiseries extérieures.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-20', category: 'divers',
    title: 'Autocontrôle — Isolation Toiture-Terrasse',
    desc: 'Fiche autocontrôle pour la réception de l\'isolation d\'une toiture-terrasse.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Isolation Toiture-terrasse.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-21', category: 'divers',
    title: 'Autocontrôle — Isolation des Combles Aménagés',
    desc: 'Fiche autocontrôle pour la réception de l\'isolation des combles aménagés.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Isolation des combles aménagés.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-22', category: 'divers',
    title: 'Autocontrôle — Isolation des Combles Perdus',
    desc: 'Fiche autocontrôle pour la réception de l\'isolation des combles perdus.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Isolation des combles perdus.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-23', category: 'divers',
    title: 'Autocontrôle — Isolation Extérieure en Toiture (Sarking)',
    desc: 'Fiche autocontrôle pour la réception d\'une isolation extérieure en toiture par sarking.',
    type: TYPE.AUTOCONTR, url: B('divers', 'Fiche Autocontrôle Isolation extérieure en toiture (Sarking).pdf'),
    source: 'PACTE',
  },
  // Guides ventilation
  {
    id: 'div-24', category: 'divers',
    title: 'Ventilation par Insufflation en Habitat Individuel',
    desc: 'Guide complet sur la ventilation par insufflation en habitat individuel.',
    type: TYPE.GUIDE, url: B('divers', 'Guide VENTILATION PAR INSUFFLATION en habitat individuel.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-25', category: 'divers',
    title: 'Guide — Pompes à Chaleur Hybrides (Logement Individuel)',
    desc: 'Analyse de l\'offre des pompes à chaleur hybrides destinées au logement individuel.',
    type: TYPE.GUIDE, url: B('divers', 'Guide _ Pompes à chaleur hybrides destinées au logement individuel – Analyse de l\'offre.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-26', category: 'divers',
    title: 'Guide — Rénovation du Bâti et Biodiversité',
    desc: 'Guide technique sur la prise en compte de la biodiversité lors de la rénovation du bâti.',
    type: TYPE.GUIDE, url: B('divers', 'Guide technique _ Rénovation du Bâti et biodiversité.pdf'),
    source: 'LPO / AQC',
  },
  {
    id: 'div-27', category: 'divers',
    title: 'ITE en Rénovation — 12 Enseignements à Connaître',
    desc: '12 enseignements clés sur l\'isolation thermique par l\'extérieur en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'ITE en rénovation - 12 enseignements à connaître.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-28', category: 'divers',
    title: 'Isolation des Combles Perdus par Soufflage — 12 Enseignements',
    desc: '12 enseignements clés sur l\'isolation des combles perdus par soufflage.',
    type: TYPE.GUIDE, url: B('divers', 'Isolation des combles perdus par soufflage - 12 enseignements à connaitre.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-29', category: 'divers',
    title: 'Isolation des Rampants en Rénovation — 12 Enseignements',
    desc: '12 enseignements clés sur l\'isolation des rampants en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Isolation des rampants en rénovation - 12 enseignements à connaître.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-30', category: 'divers',
    title: 'Isolation en Sous-Face des Planchers Bas (Neuf & Rénovation)',
    desc: 'Guide complet sur l\'isolation en sous-face des planchers bas, applicable en neuf et en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Isolation en sous-face des planchers bas - Neuf et Rénovation.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-31', category: 'divers',
    title: 'Isolation Thermique par l\'Intérieur (Neuf)',
    desc: 'Guide de référence sur l\'isolation thermique par l\'intérieur en construction neuve.',
    type: TYPE.GUIDE, url: B('divers', 'Isolation thermique par l\'intérieur - Neuf.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-32', category: 'divers',
    title: 'Isolation Thermique par l\'Intérieur (Rénovation)',
    desc: 'Guide de référence sur l\'isolation thermique par l\'intérieur en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Isolation thermique par l\'intérieur - Rénovation.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-33', category: 'divers',
    title: 'Matériaux Biosourcés — 12 Enseignements à Connaître',
    desc: '12 enseignements clés sur l\'utilisation des matériaux biosourcés dans la construction.',
    type: TYPE.GUIDE, url: B('divers', 'Matériaux biosourcés _ 12 enseignements à connaître.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-34', category: 'divers',
    title: 'Mémo Chantier — Remplacement des Menuiseries Extérieures',
    desc: 'Mémo chantier sur les points de vigilance lors du remplacement des menuiseries extérieures.',
    type: TYPE.MEMO, url: B('divers', 'MEMO CHANTIER - Remplacement des menuiseries extérieures.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-35', category: 'divers',
    title: 'Menuiseries Extérieures avec ITE — Neuf & Rénovation',
    desc: 'Guide sur la pose des menuiseries extérieures en contexte d\'isolation thermique par l\'extérieur.',
    type: TYPE.GUIDE, url: B('divers', 'Menuiseries extérieures avec une isolation thermique par l\'extérieur - Neuf et Rénovation.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-36', category: 'divers',
    title: 'Maçonneries Isolantes avec ITI — Calepin de Chantier',
    desc: 'Calepin de chantier pour les maçonneries isolantes avec isolation thermique intérieure ou répartie.',
    type: TYPE.CALEPIN, url: B('divers', 'Maçonneries isolantes avec ITI ou répartie - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-37', category: 'divers',
    title: 'Mur Double avec ITE — Calepin de Chantier',
    desc: 'Calepin de chantier pour la réalisation de murs doubles avec isolation thermique par l\'extérieur.',
    type: TYPE.CALEPIN, url: B('divers', 'Mur double avec ITE - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  // PV Réception
  {
    id: 'div-38', category: 'divers',
    title: 'PV Réception — Fenêtres de Toit',
    desc: 'Procès-verbal de réception des travaux pour la pose de fenêtres de toit.',
    type: TYPE.PV, url: B('divers', 'PV Réception travaux - Fenêtres de toit.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-39', category: 'divers',
    title: 'PV Réception — Isolation des Combles Aménagés',
    desc: 'Procès-verbal de réception des travaux d\'isolation des combles aménagés.',
    type: TYPE.PV, url: B('divers', 'PV Réception travaux - Isolation des combles aménagés.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-40', category: 'divers',
    title: 'PV Réception — Isolation des Combles Perdus',
    desc: 'Procès-verbal de réception des travaux d\'isolation des combles perdus.',
    type: TYPE.PV, url: B('divers', 'PV Réception travaux - Isolation des combles perdus.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-41', category: 'divers',
    title: 'PV Réception — Isolation Toiture-Terrasse',
    desc: 'Procès-verbal de réception des travaux d\'isolation d\'une toiture-terrasse.',
    type: TYPE.PV, url: B('divers', 'PV Réception travaux - Isolation d\'une toiture terrasse.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-42', category: 'divers',
    title: 'PV Réception — Menuiseries Extérieures & Fenêtres',
    desc: 'Procès-verbal de réception des travaux de remplacement des menuiseries extérieures et fenêtres.',
    type: TYPE.PV, url: B('divers', 'PV Réception travaux - Menuiseries extérieures et fenêtres.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-43', category: 'divers',
    title: 'Planchers Collaborants Acier-Béton — Conception & Réalisation',
    desc: 'Guide de conception et réalisation des planchers collaborants acier-béton.',
    type: TYPE.GUIDE, url: B('divers', 'Planchers collaborants acier béton - Conception et réalisation.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-44', category: 'divers',
    title: 'Planchers Mixtes Bois-Béton — Calepin de Chantier',
    desc: 'Calepin de chantier pour la réalisation de planchers mixtes bois-béton.',
    type: TYPE.CALEPIN, url: B('divers', 'Planchers mixtes bois béton - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-45', category: 'divers',
    title: 'Planchers Mixtes Bois-Béton — Mise en Œuvre (Neuf)',
    desc: 'Guide de mise en œuvre et isolation des planchers mixtes bois-béton en construction neuve.',
    type: TYPE.GUIDE, url: B('divers', 'Planchers mixtes bois-béton - Mise en œuvre et isolation - Neuf.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-46', category: 'divers',
    title: 'Planchers Mixtes Bois-Béton — Mise en Œuvre (Rénovation)',
    desc: 'Guide de mise en œuvre et isolation des planchers mixtes bois-béton en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'Planchers mixtes bois-béton - Mise en œuvre et isolation - Rénovation.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-47', category: 'divers',
    title: 'Planchers à Poutrelles & Entrevous — Calepin de Chantier',
    desc: 'Calepin de chantier pour la réalisation de planchers à poutrelles et entrevous.',
    type: TYPE.CALEPIN, url: B('divers', 'Planchers à poutrelles et entrevous - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-48', category: 'divers',
    title: 'PAC Air/Air en Habitat Individuel — Calepin',
    desc: 'Calepin de chantier pour l\'installation des pompes à chaleur air/air en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'Pompes à chaleur Air _ Air en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-49', category: 'divers',
    title: 'PAC Air/Eau en Habitat Individuel — Calepin',
    desc: 'Calepin de chantier pour l\'installation des pompes à chaleur air/eau en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'Pompes à chaleur Air _ Eau en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-50', category: 'divers',
    title: 'PAC Double Service en Habitat Individuel — Calepin',
    desc: 'Calepin de chantier pour l\'installation des pompes à chaleur double service en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'Pompes à chaleur double service en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-51', category: 'divers',
    title: 'PAC Géothermiques en Habitat Individuel — Calepin',
    desc: 'Calepin de chantier pour l\'installation des pompes à chaleur géothermiques en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'Pompes à chaleur géothermiques en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-52', category: 'divers',
    title: 'ITE par Bardage Ventilé — Calepin de Chantier',
    desc: 'Calepin de chantier pour la réalisation d\'une ITE par bardage ventilé.',
    type: TYPE.CALEPIN, url: B('divers', 'Procédés d\'ITE par bardage ventilé - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-53', category: 'divers',
    title: 'ITE par Enduit sur PSE — Calepin de Chantier',
    desc: 'Calepin de chantier pour la réalisation d\'une ITE par enduit sur polystyrène expansé.',
    type: TYPE.CALEPIN, url: B('divers', 'Procédés d\'ITE par enduit sur polystyrène expansé - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-54', category: 'divers',
    title: 'Ravalement — Obligation d\'Isolation',
    desc: 'Guide sur l\'obligation d\'isolation lors de travaux de ravalement, rénovation de toiture ou aménagement.',
    type: TYPE.GUIDE, url: B('divers', 'Ravalement, rénovation de toiture, aménagement de pièces _ l\'obligation d\'isolation.pdf'),
    source: 'ADEME',
  },
  {
    id: 'div-55', category: 'divers',
    title: 'Rénovation Performante par Étapes (Logement Individuel)',
    desc: 'Guide sur la stratégie de rénovation performante par étapes en logement individuel.',
    type: TYPE.GUIDE, url: B('divers', 'Rénovation performante par étapes en logement individuel.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-56', category: 'divers',
    title: 'Rénovation Thermique Performante par Étapes',
    desc: 'Guide sur la rénovation thermique performante réalisée par étapes successives.',
    type: TYPE.GUIDE, url: B('divers', 'Rénovation thermique performante par étapes.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-57', category: 'divers',
    title: 'Rénover ses Fenêtres',
    desc: 'Guide pratique pour la rénovation des fenêtres : choix, types de vitrage, poses.',
    type: TYPE.GUIDE, url: B('divers', 'Rénover ses fenetres.pdf'),
    source: 'ADEME',
  },
  {
    id: 'div-58', category: 'divers',
    title: 'Rénover ses Volets',
    desc: 'Guide pratique pour la rénovation des volets : choix des matériaux et mise en œuvre.',
    type: TYPE.GUIDE, url: B('divers', 'Rénover ses volets.pdf'),
    source: 'ADEME',
  },
  {
    id: 'div-59', category: 'divers',
    title: 'Schémathèque — Chauffage au Bois Bûches (Habitat Individuel)',
    desc: 'Schémathèque des appareils de chauffage au bois bûches en habitat individuel.',
    type: TYPE.SCHEMAS, url: B('divers', 'Schémathèque _ Appareils de chauffage au bois bûches en habitat individuel.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-60', category: 'divers',
    title: 'Schémathèque — Chauffage aux Granulés (Habitat Individuel)',
    desc: 'Schémathèque des appareils de chauffage aux granulés en habitat individuel.',
    type: TYPE.SCHEMAS, url: B('divers', 'Schémathèque _ Appareils de chauffage aux granulés en habitat individuel.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-61', category: 'divers',
    title: 'Schémathèque — Systèmes Solaires (Habitat Individuel)',
    desc: 'Schémathèque des systèmes solaires thermiques en habitat individuel.',
    type: TYPE.SCHEMAS, url: B('divers', 'Schémathèque _ Systèmes solaires en habitat individuel.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-62', category: 'divers',
    title: 'Systèmes Solaires Combinés — Calepin de Chantier',
    desc: 'Calepin de chantier pour l\'installation des systèmes solaires combinés en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'Systèmes solaires combinés en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-63', category: 'divers',
    title: 'Toitures-Terrasses Bois Isolées Sous Élément Porteur (Neuf)',
    desc: 'Guide technique sur les toitures-terrasses bois isolées intégralement sous l\'élément porteur en neuf.',
    type: TYPE.GUIDE, url: B('divers', 'TOITURES-TERRASSES EN BOIS ISOLÉES INTÉGRALEMENT SOUS L\'ÉLÉMENT PORTEUR - NEUF.pdf'),
    source: 'CSTB',
  },
  {
    id: 'div-64', category: 'divers',
    title: 'Étanchéité & Isolation des Toitures-Terrasses Bois — Calepin',
    desc: 'Calepin de chantier pour l\'étanchéité et l\'isolation thermique des toitures-terrasses bois.',
    type: TYPE.CALEPIN, url: B('divers', 'Étanchéité et isolation thermique des toitures-terrasses bois - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-65', category: 'divers',
    title: 'VMC Double Flux en Rénovation — 12 Enseignements',
    desc: '12 enseignements clés sur la VMC double flux en rénovation.',
    type: TYPE.GUIDE, url: B('divers', 'VMC DOUBLE FLUX en rénovation - 12 enseignements à connaître.pdf'),
    source: 'AQC',
  },
  {
    id: 'div-66', category: 'divers',
    title: 'VMC Double Flux en Habitat Individuel — Guide Complet',
    desc: 'Guide complet sur la VMC double flux : conception, installation et entretien en habitat individuel.',
    type: TYPE.GUIDE, url: B('divers', 'VMC Double flux en habitat individuel - conception et dimensionnement; installation et mise en service; entretien et maintenance.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-67', category: 'divers',
    title: 'VMC Double Flux — Calepin de Chantier',
    desc: 'Calepin de chantier pour l\'installation de la VMC double flux en habitat individuel.',
    type: TYPE.CALEPIN, url: B('divers', 'VMC double flux en habitat individuel - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-68', category: 'divers',
    title: 'VMC Simple Flux en Rénovation — Habitat Collectif',
    desc: 'Guide sur la VMC simple flux en rénovation pour les logements collectifs.',
    type: TYPE.GUIDE, url: B('divers', 'VMC simple flux en rénovation - Habitat collectif.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-69', category: 'divers',
    title: 'Ventilation Mécanique Répartie — Calepin de Chantier',
    desc: 'Calepin de chantier pour la ventilation mécanique répartie en rénovation.',
    type: TYPE.CALEPIN, url: B('divers', 'Ventilation mécanique répartie en rénovation - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-70', category: 'divers',
    title: 'Guide — Rénovation Énergétique du Bâti Ancien',
    desc: 'Guide complet pour la rénovation énergétique des bâtiments anciens.',
    type: TYPE.GUIDE, url: B('divers', 'Guide pour la rénovation énergétique des bâtiments anciens.pdf'),
    source: 'ADEME',
  },
  {
    id: 'div-71', category: 'divers',
    title: 'Calepin Interface — Combles Perdus / Mur Isolé Intérieur',
    desc: 'Calepin interfaces pour la rénovation globale : combles perdus et mur isolé par l\'intérieur.',
    type: TYPE.CALEPIN, url: B('divers', 'Calepin Interface _ Combles perdus _ Mur isolé par l\'intérieur - Rénovation globale.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-72', category: 'divers',
    title: 'Calepin Interface — Sarking & Mur Pignon ITI',
    desc: 'Calepin interfaces pour la rénovation globale : sarking et mur pignon isolé par l\'intérieur.',
    type: TYPE.CALEPIN, url: B('divers', 'Calepin Interface _ Sarking et mur pignon isolé par l\'intérieur (ITI) - Rénovation globale.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-73', category: 'divers',
    title: 'Revêtements Extérieurs en Bois & ITE — Calepin',
    desc: 'Calepin de chantier pour les revêtements extérieurs en bois en contexte d\'ITE.',
    type: TYPE.CALEPIN, url: B('divers', 'Revêtements extérieurs en bois et ITE - Calepin de chantier.pdf'),
    source: 'PACTE',
  },
  {
    id: 'div-74', category: 'divers',
    title: 'Guide — Menuiserie Toulousaine (DRAC)',
    desc: 'Guide DRAC sur les spécificités de la menuiserie toulousaine, patrimoine et mise en œuvre.',
    type: TYPE.GUIDE, url: B('divers', 'DRAC - Guide de la Menuiserie Toulousaine.pdf'),
    source: 'DRAC',
  },
  {
    id: 'div-75', category: 'divers',
    title: 'Installer un Climatiseur',
    desc: 'Guide pratique pour l\'installation d\'un climatiseur : choix, réglementation, mise en œuvre.',
    type: TYPE.GUIDE, url: B('divers', 'Installer un climatiseur.pdf'),
    source: 'ADEME',
  },

  /* ══════════════════════════════════════════════════════
     TUTORIELS VIDÉO REX BP (30 vidéos)
  ══════════════════════════════════════════════════════ */
  { id: 'vid-01', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation des rampants en rénovation [1/3]',
    desc: 'Principes de base et enjeux de l\'isolation des combles aménagés en rénovation.',
    url: 'https://www.youtube.com/watch?v=k3JStfTaAus&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=1',
    ytId: 'k3JStfTaAus', serie: 'Isolation des rampants', part: 1,
  },
  { id: 'vid-02', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation des rampants en rénovation [2/3]',
    desc: 'Points de vigilance pour concevoir et réaliser une isolation sous toiture durable.',
    url: 'https://www.youtube.com/watch?v=sgTe1tUBDPY&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=2',
    ytId: 'sgTe1tUBDPY', serie: 'Isolation des rampants', part: 2,
  },
  { id: 'vid-03', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation des rampants en rénovation [3/3]',
    desc: 'Retours d\'expérience et prévention des désordres liés aux rampants.',
    url: 'https://www.youtube.com/watch?v=z7h8Rqt9d9o&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=3',
    ytId: 'z7h8Rqt9d9o', serie: 'Isolation des rampants', part: 3,
  },
  { id: 'vid-04', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation simple flux en rénovation [1/3]',
    desc: 'Rôle de la VMC simple flux dans un logement rénové et plus étanche.',
    url: 'https://www.youtube.com/watch?v=YE5EmQmT9_s&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=4',
    ytId: 'YE5EmQmT9_s', serie: 'Ventilation simple flux', part: 1,
  },
  { id: 'vid-05', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation simple flux en rénovation [2/3]',
    desc: 'Bonnes pratiques de conception et de mise en œuvre du réseau de ventilation.',
    url: 'https://www.youtube.com/watch?v=lYTSWP6Qle0&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=5',
    ytId: 'lYTSWP6Qle0', serie: 'Ventilation simple flux', part: 2,
  },
  { id: 'vid-06', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation simple flux en rénovation [3/3]',
    desc: 'Erreurs courantes, contrôles et performances à vérifier à la réception.',
    url: 'https://www.youtube.com/watch?v=vgvtWKDW_6M&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=6',
    ytId: 'vgvtWKDW_6M', serie: 'Ventilation simple flux', part: 3,
  },
  { id: 'vid-07', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation double flux en rénovation [1/3]',
    desc: 'Fonctionnement, intérêt et conditions d\'emploi d\'une VMC double flux.',
    url: 'https://www.youtube.com/watch?v=LhDYsDiN2F0&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=7',
    ytId: 'LhDYsDiN2F0', serie: 'Ventilation double flux', part: 1,
  },
  { id: 'vid-08', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation double flux en rénovation [2/3]',
    desc: 'Dimensionnement et pose des équipements et réseaux de double flux.',
    url: 'https://www.youtube.com/watch?v=IwymEbx4jDM&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=8',
    ytId: 'IwymEbx4jDM', serie: 'Ventilation double flux', part: 2,
  },
  { id: 'vid-09', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'La ventilation double flux en rénovation [3/3]',
    desc: 'Points de contrôle, entretien et limites observées sur chantier.',
    url: 'https://www.youtube.com/watch?v=_vQswvzx0II&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=9',
    ytId: '_vQswvzx0II', serie: 'Ventilation double flux', part: 3,
  },
  { id: 'vid-10', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chauffe-eau thermodynamique en rénovation [1/3]',
    desc: 'Présentation du chauffe-eau thermodynamique et de son fonctionnement.',
    url: 'https://www.youtube.com/watch?v=1AxJZHPSq7E&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=10',
    ytId: '1AxJZHPSq7E', serie: 'Chauffe-eau thermodynamique', part: 1,
  },
  { id: 'vid-11', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chauffe-eau thermodynamique en rénovation [2/3]',
    desc: 'Implantation, raccordements et précautions de mise en œuvre.',
    url: 'https://www.youtube.com/watch?v=N1QJxEnavOI&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=11',
    ytId: 'N1QJxEnavOI', serie: 'Chauffe-eau thermodynamique', part: 2,
  },
  { id: 'vid-12', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chauffe-eau thermodynamique en rénovation [3/3]',
    desc: 'Dysfonctionnements possibles et recommandations pour préserver les performances.',
    url: 'https://www.youtube.com/watch?v=sBW-LS-zJuI&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=12',
    ytId: 'sBW-LS-zJuI', serie: 'Chauffe-eau thermodynamique', part: 3,
  },
  { id: 'vid-13', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation en sous-face des planchers bas [1/3]',
    desc: 'Intérêt d\'isoler les planchers sur vide sanitaire, cave ou local non chauffé.',
    url: 'https://www.youtube.com/watch?v=8iSnOTBxR4w&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=13',
    ytId: '8iSnOTBxR4w', serie: 'Isolation planchers bas', part: 1,
  },
  { id: 'vid-14', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation en sous-face des planchers bas [2/3]',
    desc: 'Choix des solutions et détails de pose en sous-face.',
    url: 'https://www.youtube.com/watch?v=k9YHMPOvxyk&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=14',
    ytId: 'k9YHMPOvxyk', serie: 'Isolation planchers bas', part: 2,
  },
  { id: 'vid-15', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'isolation en sous-face des planchers bas [3/3]',
    desc: 'Traitement des points singuliers, risques d\'humidité et qualité d\'exécution.',
    url: 'https://www.youtube.com/watch?v=6l8bJaJCbeg&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=15',
    ytId: '6l8bJaJCbeg', serie: 'Isolation planchers bas', part: 3,
  },
  { id: 'vid-16', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'ITE en rénovation [1/3]',
    desc: 'Principes de l\'isolation thermique par l\'extérieur en rénovation.',
    url: 'https://www.youtube.com/watch?v=ViZZSYAWQm4&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=16',
    ytId: 'ViZZSYAWQm4', serie: 'ITE en rénovation', part: 1,
  },
  { id: 'vid-17', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'ITE en rénovation [2/3]',
    desc: 'Préparation du support, traitement des façades et mise en œuvre des systèmes.',
    url: 'https://www.youtube.com/watch?v=CMH5IAa8OO8&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=17',
    ytId: 'CMH5IAa8OO8', serie: 'ITE en rénovation', part: 2,
  },
  { id: 'vid-18', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'ITE en rénovation [3/3]',
    desc: 'Gestion des ouvertures, soubassements et autres détails sensibles.',
    url: 'https://www.youtube.com/watch?v=JLmF15PJkF8&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=18',
    ytId: 'JLmF15PJkF8', serie: 'ITE en rénovation', part: 3,
  },
  { id: 'vid-19', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'éclairage artificiel en rénovation [1/3]',
    desc: 'Bases pour améliorer l\'éclairage artificiel lors d\'une rénovation.',
    url: 'https://www.youtube.com/watch?v=NUp3HhtR0MA&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=19',
    ytId: 'NUp3HhtR0MA', serie: 'Éclairage artificiel', part: 1,
  },
  { id: 'vid-20', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'éclairage artificiel en rénovation [2/3]',
    desc: 'Choix et implantation des luminaires selon les usages des pièces.',
    url: 'https://www.youtube.com/watch?v=haiUMdoB3yc&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=20',
    ytId: 'haiUMdoB3yc', serie: 'Éclairage artificiel', part: 2,
  },
  { id: 'vid-21', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'L\'éclairage artificiel en rénovation [3/3]',
    desc: 'Performance, confort visuel et erreurs à éviter dans un projet rénové.',
    url: 'https://www.youtube.com/watch?v=92VmW9CR5Jc&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=21',
    ytId: '92VmW9CR5Jc', serie: 'Éclairage artificiel', part: 3,
  },
  { id: 'vid-22', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chaufferie bois en rénovation [1/3]',
    desc: 'Présentation des solutions de chaufferie bois en rénovation.',
    url: 'https://www.youtube.com/watch?v=iObb8Q4xMNU&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=22',
    ytId: 'iObb8Q4xMNU', serie: 'Chaufferie bois', part: 1,
  },
  { id: 'vid-23', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chaufferie bois en rénovation [2/3]',
    desc: 'Conception de l\'installation : local, hydraulique, fumisterie et stockage.',
    url: 'https://www.youtube.com/watch?v=xnir-Em5k4k&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=23',
    ytId: 'xnir-Em5k4k', serie: 'Chaufferie bois', part: 2,
  },
  { id: 'vid-24', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Chaufferie bois en rénovation [3/3]',
    desc: 'Exploitation, réglages et prévention des dysfonctionnements.',
    url: 'https://www.youtube.com/watch?v=z6aJeYzJJIk&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=24',
    ytId: 'z6aJeYzJJIk', serie: 'Chaufferie bois', part: 3,
  },
  { id: 'vid-25', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Pompe à chaleur en rénovation [1/3]',
    desc: 'Comprendre le rôle et les conditions de performance d\'une PAC en rénovation.',
    url: 'https://www.youtube.com/watch?v=ukMscRzeJAo&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=25',
    ytId: 'ukMscRzeJAo', serie: 'Pompe à chaleur', part: 1,
  },
  { id: 'vid-26', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Pompe à chaleur en rénovation [2/3]',
    desc: 'Dimensionnement et intégration de la PAC avec les émetteurs existants.',
    url: 'https://www.youtube.com/watch?v=iZ1xL4IC0n8&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=26',
    ytId: 'iZ1xL4IC0n8', serie: 'Pompe à chaleur', part: 2,
  },
  { id: 'vid-27', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Pompe à chaleur en rénovation [3/3]',
    desc: 'Réglages, mise en service et défauts pouvant dégrader le rendement.',
    url: 'https://www.youtube.com/watch?v=uvfILVJ2bTU&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=27',
    ytId: 'uvfILVJ2bTU', serie: 'Pompe à chaleur', part: 3,
  },
  { id: 'vid-28', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Conception & dimensionnement des équipements [1/3]',
    desc: 'Méthode générale pour concevoir les équipements techniques d\'un projet rénové.',
    url: 'https://www.youtube.com/watch?v=2cSHekBj6Ik&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=28',
    ytId: '2cSHekBj6Ik', serie: 'Conception équipements', part: 1,
  },
  { id: 'vid-29', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Conception & dimensionnement des équipements [2/3]',
    desc: 'Adapter les puissances et équipements aux besoins réels du bâtiment.',
    url: 'https://www.youtube.com/watch?v=E5Dvjg1aOLg&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=29',
    ytId: 'E5Dvjg1aOLg', serie: 'Conception équipements', part: 2,
  },
  { id: 'vid-30', category: 'videos', type: TYPE.VIDEO, source: 'AQC / REX BP',
    title: 'Conception & dimensionnement des équipements [3/3]',
    desc: 'Coordination des lots, vérifications finales et prévention du surdimensionnement.',
    url: 'https://www.youtube.com/watch?v=dzaXF34r-ZM&list=PLAJ9gAxB6qf0KKaySanrqVwbnxVzcEBk1&index=30',
    ytId: 'dzaXF34r-ZM', serie: 'Conception équipements', part: 3,
  },
]

/** Retourne le nombre de documents par catégorie (hors 'toutes') */
export function getCountByCategory(slug) {
  return RESOURCES.filter(r => r.category === slug).length
}

/** Total de documents */
export const TOTAL_DOCS = RESOURCES.filter(r => r.category !== 'videos').length
export const TOTAL_VIDEOS = RESOURCES.filter(r => r.category === 'videos').length

// Ajout des prix dynamiques basés sur le nombre de pages et stats virtuelles
RESOURCES.forEach(r => {
  if (r.category !== 'videos') {
    const parts = r.url.split('/')
    let filename = decodeURIComponent(parts[parts.length - 1])
    
    const pages = pagesMap[filename] || 1
    r.pages = pages
    // Formule: 1.00€ + 0.10€ par page
    r.price = Math.round((1.00 + (pages * 0.10)) * 100) / 100
    
    // Téléchargements virtuels déterministes (basés sur le nom)
    let charSum = 0
    for(let i=0; i<filename.length; i++) charSum += filename.charCodeAt(i)
    r.downloads = (charSum % 850) + 120 // Entre 120 et 970
  }
})
